<?php

namespace App\Command;

use App\Entity\Category;
use App\Entity\Competition\Competition;
use App\Helper\SlugHelper\CharMapping;
use App\Helper\SlugHelper\SlugHelper;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Validator\Constraints\Date;

class TestCommand extends Command
{
    private \DateTime $time;


    protected EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        parent::__construct('test');
        $this->entityManager = $entityManager;
    }

    public function execute(InputInterface $input, OutputInterface $output)
    {
        $this->time = new \DateTime('2002-6-1 19:00:00');
        $this->time->format('y-m-d h:i:s');
        var_dump($this->time);

        die;


        die;
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}
